"""Serves data/flowers.json - the ornamental catalog behind the /flowers
atlas and the /match matchmaker.

The file is generated by scripts/build_flowers_json.py and loaded once into
memory (it is small, ~100KB) so every page and every match request reads
from the same cache.
"""
import json
import os

_FLOWERS_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "data", "flowers.json")
_catalog_cache = None


def load_catalog() -> dict:
    """Full catalog: {note, generated_by, groups, flowers}."""
    global _catalog_cache
    if _catalog_cache is None:
        with open(_FLOWERS_PATH, "r", encoding="utf-8") as fh:
            _catalog_cache = json.load(fh)
    return _catalog_cache


def all_flowers():
    return load_catalog()["flowers"]


def all_groups():
    return load_catalog()["groups"]


def by_slug(slug: str):
    slug = (slug or "").strip().lower()
    for flower in all_flowers():
        if flower["slug"] == slug:
            return flower
    return None
